### ISSUE TITLE
Blank html report

### ISSUE THREAD

**Issue by dhruvservana** [yebinama/paclair#18]
Dear team,

Below command was able to retrieve JSON from Clair V3 server.
paclair --conf conf/conf.yml Docker ubuntu analyse 

But the below command pulls the blank html report. am I missing something?

paclair --conf conf/conf.yml Docker ubuntu analyse --output-format html --output-dir /tmp

**Comment by dhruvservana** [comment]
Created pull https://github.com/yebinama/paclair/pull/19 to solve this issue

**Comment by yebinama** [comment]
Hi,

Thanks for the report. 
It seems that Clair's v3 api has changed since I developped the compatibility:
https://github.com/coreos/clair/commit/6a44052e3161f572d42a30430487052f7735a9e3

I'll review your PR to fix the bug.

**Comment by dhruvservana** [comment]
Thank you! Appreciate your help

**Comment by dhruvservana** [comment]
did you get a chance to review this?
