### ISSUE TITLE
Question - Is it possible to scan local build images?

### ISSUE THREAD

**Issue by pipozzz** [yebinama/paclair#22]
Hello, 
Is it possible to scan locally build images ?

Thanks

**Comment by yebinama** [comment]
Hello,

Unfortunately this feature is not yet available. The application needs to interact with a registry to download the image.

**Comment by pipozzz** [comment]
You mean paclair reads image from repository and then pushes to clair? or is there something different?

**Comment by yebinama** [comment]
Paclair reads the manifest from the registry and then send to clair each layer url.
