### ISSUE TITLE
Question - Is it possible to scan images with tag? 

### ISSUE THREAD

**Issue by Anemone95** [yebinama/paclair#26]
For example, if I want to scan `medicean/vulapps:s_struts2_s2-037`, how to push it? I tried `paclair --debug --conf paclair.yml Docker medicean/vulapps:s_struts2_s2-037 push` to push it, but it returned "not found".

**Comment by yebinama** [comment]
@Anemone95 
It should work the way you try it.
Can you paste the debug logs?

**Comment by Anemone95** [comment]
Sorry, it actually works. The previous error may be due to network error.
